# Generated by Django 4.0.5 on 2024-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('accident_type', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Severe', 'Severe')], max_length=50)),
                ('injury_severity', models.CharField(choices=[('None', 'None'), ('Mild', 'Mild'), ('Severe', 'Severe')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
