# Generated by Django 4.0.5 on 2024-10-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lead_driver_fault'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='commercial_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='fracture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='passenger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='pedestrian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='rear_end',
            field=models.BooleanField(default=False),
        ),
    ]
