# Generated by Django 4.0.5 on 2024-10-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_lead_accident_type_remove_lead_driver_fault_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='insured',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
    ]
