# Generated by Django 4.0.5 on 2024-11-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_lead_language_spoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='commercial_vehicle',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='injured',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='insured',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passenger',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pedestrian',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='rear_end',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
    ]
